### ISSUE TITLE
Uso de WebP

### ISSUE THREAD

**Issue by jrosell** [optimizacion-imagenes/AMA#1]
Todo hace pensar que Safari va acabar dando soporte a WebP. ¿Hoy en día tiene sentido plantearse usar únicamente el formato WebP usando alguna libreria javascript que nos de soporte a WebP en navegadores que no lo tienen? (webp-hero, webpjs...)

**Comment by jrosell** [comment]
Mi pregunta va relacionada sobretodo a cuando no puedes usar elemento picture, pq usas background-img @nucliweb

**Comment by nucliweb** [comment]
Sorry @jrosell, no sé el motivo por el que no recibo notificaciones de este repo 😓.

En ese caso yo utilizo PostCSS, que puedes usar después de Sass (por ejemplo) , igual que lo hacer con Autoprefixer.

Para WebP puede usar [webp-in-css](https://github.com/ai/webp-in-css) del propio autor de PostCSS.

### Bonus

Hace poco publiqué el mismo plugin pero para el formato de imágenes AVIF, [vif-in-css](https://github.com/nucliweb/avif-in-css)
